# backend/routers/insights_router.py — v3.0
"""
AION Analytics — Insights Router (Nightly + Multi-Layer)

Delivers all Top-50 insight boards generated by:
    backend/services/insights_builder.py (v3.0)

Boards:
    • top50_1w.json
    • top50_2w.json
    • top50_4w.json
    • top50_52w.json
    • top50_social_heat.json
    • top50_news_novelty.json

Features:
    • API selection: board=1w,2w,4w,52w,social,news
    • Filtering: sector=..., minConfidence=...
    • Sorted by score (default)
    • Fallback to Rolling if JSON missing
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from fastapi import APIRouter, Query

from backend.core.config import PATHS
from backend.core.data_pipeline import _read_rolling, log
from backend.services.insights_builder import build_daily_insights

router = APIRouter(prefix="/insights", tags=["Insights"])

# Map API names → actual filenames generated by insights_builder
BOARD_MAP = {
    "1w": "top50_1w.json",
    "2w": "top50_2w.json",
    "4w": "top50_4w.json",
    "52w": "top50_52w.json",
    "social": "top50_social_heat.json",
    "news": "top50_news_novelty.json",
}

INSIGHTS_DIR: Path = PATHS.get("insights", PATHS.get("root", Path(".")) / "insights")


# ---------------------------------------------------------------------
# INTERNAL HELPERS
# ---------------------------------------------------------------------

def _load_board(file_name: str) -> dict | None:
    p = INSIGHTS_DIR / file_name
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception as e:
        log(f"[insights_router] ⚠️ Failed to load {file_name}: {e}")
        return None


def _filter_items(items: list, sector: str | None, min_conf: float | None) -> list:
    out = []
    for row in items:
        if sector and row.get("sector") != sector:
            continue
        if min_conf is not None:
            conf = row.get("confidence") or row.get("avg_confidence") or 0.0
            if conf < min_conf:
                continue
        out.append(row)
    return out


# ---------------------------------------------------------------------
# MAIN ROUTE
# ---------------------------------------------------------------------

@router.get("/")
async def get_insights(
    board: str = Query(
        "1w",
        description="Insight board: 1w | 2w | 4w | 52w | social | news",
    ),
    limit: int = Query(50, description="Number of items to return."),
    sector: str | None = Query(None, description="Filter by sector."),
    minConfidence: float | None = Query(
        None, description="Filter by minimum confidence (0–1)."
    ),
):
    """
    Returns an insight board (Top-N) generated by nightly insights_builder.

    If board JSON is missing → tries to rebuild insights.
    If builder fails → fallback to simplified Rolling-based insights.
    """

    board = board.lower()
    if board not in BOARD_MAP:
        return {"error": f"Invalid board '{board}'", "allowed": list(BOARD_MAP.keys())}

    file_name = BOARD_MAP[board]

    # ----------------------------------------------
    # Try loading existing board JSON
    # ----------------------------------------------
    js = _load_board(file_name)

    # If missing, force rebuild
    if js is None:
        log(f"[insights_router] ⚠️ Board {file_name} missing → rebuilding insights.")
        try:
            build_daily_insights(limit=limit)
            js = _load_board(file_name)
        except Exception as e:
            log(f"[insights_router] ❌ Rebuild failed: {e}")
            js = None

    # ----------------------------------------------
    # If still missing → Rolling fallback (never fails)
    # ----------------------------------------------
    if js is None:
        log(f"[insights_router] ⚠️ Fallback to Rolling for board {board}")
        rolling = _read_rolling() or {}

        rows = []
        for sym, node in rolling.items():
            if sym.startswith("_"):
                continue

            preds = node.get("predictions", {})
            if not preds:
                continue

            # Build a simplified insight row
            r = {
                "symbol": sym,
                "name": node.get("name"),
                "sector": node.get("sector"),
                "ml_score": preds.get("1d", {}).get("score"),
                "confidence": preds.get("1d", {}).get("confidence"),
            }

            # Filters
            if sector and r["sector"] != sector:
                continue
            if minConfidence and r["confidence"] is not None:
                if r["confidence"] < minConfidence:
                    continue

            rows.append(r)

        # Sort by score if available
        rows.sort(key=lambda x: x.get("ml_score", 0.0), reverse=True)
        return {
            "timestamp": datetime.utcnow().isoformat(),
            "board": board,
            "count": len(rows[:limit]),
            "items": rows[:limit],
            "source": "rolling_fallback",
        }

    # ----------------------------------------------
    # Normal path: return the board JSON
    # ----------------------------------------------
    items = js.get("items") or []
    items = _filter_items(items, sector, minConfidence)
    items = items[:limit]

    return {
        "timestamp": js.get("generated_at"),
        "board": board,
        "count": len(items),
        "items": items,
        "source": "insights_files",
    }
